<?php

// $Id: simplenews_template.tpl.php,v 1.1.2.2 2009/02/01 22:10:41 tbarregren Exp $


/**
 * @file
 * Default template for the HTML e-mail with the newsletter.
 *
 * Simplenews Template will first look in the directory of the current used
 * theme for a file named "simplenews_template.tpl.php". If it exists, it will
 * be used as template for the HTML e-mails with the newsletter issues that
 * Simplenews sends. If the file doesn't exists, this file will be used instead.
 *
 * DO NOT EDIT THIS FILE. If you want to customize the template, copy this
 * file to the directory of the used theme, and edit the copy.
 *
 * Following variables are available in the template:
 *
 *    - $node            : node with the issue of the newsletter
 *    - $newsletter_name : name of the newsletter
 *    - $issue_title     : title of the issue
 *    - $style_element   : complete <style>-element with the CSS rules
 *    - $bgcolor         : background color for the <body> element
 *
 * Resources that can be helpful:
 *
 *   - http://www.mailchimp.com/resources/
 *   - http://www.mailchimp.com/resources/templates/
 *   - http://www.campaignmonitor.com/css/
 *   - http://www.campaignmonitor.com/gallery/
 */

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<meta HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=utf-8">
<title><?php echo "$newsletter_name: $issue_title"; ?></title>
</head>
<body bgcolor="<?php echo $bgcolor; ?>">
<?php echo $style_element; ?>
<table class="simplenews-template-background" width="100%" bgcolor="<?php echo $bgcolor; ?>" cellpadding="0" cellspacing="0"><tr><td valign="top" align="center">
<table class="simplenews-template-content" cellpadding="0" cellspacing="0"><tr><td>
<h1><span class="newsletter-name"><?php echo $newsletter_name; ?>: </span><span class="issue-title"><?php echo $issue_title; ?></span></h1>
<?php echo $node->body; ?>
</td></tr></table>
</td></tr></table>
</body>
</html>
