<?php

define('JOB_PERM_VIEW', 'view jobs');

function job_access_node_grants($account, $op) {
  $grants = array();
  if ($op == 'view' && user_access(JOB_PERM_VIEW, $account)) {
    $grants['job_view'] = array(1);
  }
  return $grants;
}

function job_access_node_access_records($node) {
  $grants = array();
  if (variable_get(JOB_NODE_TYPE . $node->type, 0)) {
    $grants[] = array(
      'realm' => 'job_view',
      'gid' => 1,
      'grant_view' => TRUE,
      'grant_update' => FALSE,
      'grant_delete' => FALSE,
      'priority' => 0,
    );
  }
  return $grants;
}

function job_access_perm() {
  return array(
    JOB_PERM_VIEW,
  );
}
