<?php 
/**
 * views template to output one 'row' of a view.
 * This code was generated by the views theming wizard
 * Date: Thu, 04/12/2007 - 22:14
 * View: buddylist_of_uid
 *
 * Variables available:
 * $view -- the entire view object. Important parts of this object are
 *   buddylist_of_uid, .
 * $view_type -- The type of the view. Probably 'page' or 'block' but could
 *   also be 'embed' or other string passed in from a custom view creator.
 * $node -- the raw data. This is not a real node object, but will contain
 *   the nid as well as other support fields that might be necessary.
 * $count -- the current row in the view (not TOTAL but for this page) starting
 *   from 0.
 * $stripe -- 'odd' or 'even', alternating. 
 * $uid -- Display the user picture of the author.
 * $uid_label -- The assigned label for $uid
 * $name -- This will display the name of the user.
 * $name_label -- The assigned label for $name
 * $usernode_users_uid -- Display the user id.
 * $usernode_users_uid_label -- The assigned label for $usernode_users_uid *
 */
   
  ?>
  
<div class="thumbnail">
<?php print $uid?>

<br />
<?php print l($name, "user/$usernode_users_uid")?>
</div>


